name: Build aria2 on Windows with OpenSSL

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Install Chocolatey and dependencies
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        choco install -y make autoconf automake libtool pkgconfig openssl strawberryperl git

    - name: Clone aria2 and prepare build
      run: |
        git clone https://github.com/aria2/aria2.git
        cd aria2
        git submodule update --init
        autoreconf -i

    - name: Configure build with OpenSSL
      run: |
        cd aria2
        ./configure --with-openssl --without-gnutls --enable-static=yes --enable-shared=no

    - name: Build aria2
      run: |
        cd aria2
        make -j2

    - name: Upload binary
      uses: actions/upload-artifact@master
      with:
        name: aria2-windows-openssl
        path: aria2/src/aria2c.exe
