name: Build Aria2 with PQC Support for Windows

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    env:
      OPENSSL_DIR: C:/oqs-openssl
      LIBOQS_DIR: C:/liboqs
      OQSPROV_DIR: C:/oqs-provider

    steps:
    - name: Checkout aria2
      uses: actions/checkout@v4
      with:
        repository: aria2/aria2
        path: aria2

    - name: Install dependencies
      run: |
        choco install strawberryperl -y
        choco install python3 -y
        choco install cmake ninja -y
        choco install winflexbison -y
        choco install make -y
        choco install nasm -y
        echo "C:\ProgramData\chocolatey\bin" | Out-File -Append $env:GITHUB_PATH

    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Verify NASM
      run: nasm -v

    - name: Build liboqs
      run: |
        git clone --recursive https://github.com/open-quantum-safe/liboqs.git
        cd liboqs
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.LIBOQS_DIR }} ..
        ninja -j4
        ninja install

    - name: Build OpenSSL (master)
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        perl Configure VC-WIN64A no-shared --prefix=${{ env.OPENSSL_DIR }}
        nmake
        nmake install_sw

    - name: Build oqs-provider
      run: |
        git clone https://github.com/open-quantum-safe/oqs-provider.git
        cd oqs-provider
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release `
              -DOPENSSL_ROOT_DIR=${{ env.OPENSSL_DIR }} `
              -Dliboqs_DIR=${{ env.LIBOQS_DIR }} `
              -DCMAKE_INSTALL_PREFIX=${{ env.OQSPROV_DIR }} .
        ninja -j4
        ninja install

    - name: Build aria2
      working-directory: ${{ github.workspace }}/aria2
      run: |
        autoreconf -i
        ./configure --with-openssl=${{ env.OPENSSL_DIR }} --without-gnutls --enable-static --disable-shared
        make -j4

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2-pqc-windows
        path: ${{ github.workspace }}/aria2/src/aria2c.exe
