name: Build Aria2 with PQC Support on Windows

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    env:
      LIBOQS_DIR: C:\liboqs
      OPENSSL_DIR: C:\openssl-3.5.3
      OQSPROV_DIR: C:\oqs-provider

    steps:
    - name: Checkout aria2
      uses: actions/checkout@v4
      with:
        repository: aria2/aria2
        path: aria2

    - name: Install dependencies
      run: |
        choco install cmake ninja strawberryperl nasm -y
        echo "C:\Program Files\NASM" | Out-File -Append $env:GITHUB_PATH

    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1


    - name: Build liboqs
      run: |
        git clone --recursive https://github.com/open-quantum-safe/liboqs.git
        cd liboqs
        mkdir build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.LIBOQS_DIR }} ..
        ninja -j4
        ninja install

    - name: Build OpenSSL 3.5.3
      run: |
        git clone https://github.com/openssl/openssl.git
        cd openssl
        git checkout openssl-3.5.3
        perl Configure VC-WIN64A no-shared --prefix=${{ env.OPENSSL_DIR }}
        nmake
        nmake install_sw

    - name: Build oqs-provider
      run: |
        git clone https://github.com/open-quantum-safe/oqs-provider.git
        cd oqs-provider
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release `
          -DOPENSSL_ROOT_DIR=${{ env.OPENSSL_DIR }} `
          -Dliboqs_DIR=${{ env.LIBOQS_DIR }} `
          -DCMAKE_INSTALL_PREFIX=${{ env.OQSPROV_DIR }} .
        ninja -j4
        ninja install

    # - name: Install MSYS2 and autotools
    #   run: |
    #     choco install msys2 -y
    #     echo "C:\tools\msys64\usr\bin" | Out-File -Append $env:GITHUB_PATH
    #     C:\tools\msys64\usr\bin\bash -lc "
    #       pacman -Sy --noconfirm &&
    #       pacman -S --noconfirm \
    #         base-devel autoconf automake libtool make gcc pkg-config
    #     "
    - name: Install MSYS2 and autotools
      run: |
        choco install msys2 -y
        echo "C:\tools\msys64\usr\bin" | Out-File -Append $env:GITHUB_PATH
        C:\tools\msys64\usr\bin\bash -lc "
          pacman -Sy --noconfirm &&
          pacman -S --noconfirm \
            base-devel autoconf automake libtool make gcc pkg-config \
            gettext gettext-devel
        "

    - name: Build aria2 with PQC OpenSSL
      run: |
        C:\tools\msys64\usr\bin\bash -lc "
          cd '${{ github.workspace }}/aria2' &&
          autoreconf -i &&
          ./configure \
            --with-openssl=C:/openssl-3.5.3 \
            --without-gnutls \
            --enable-static \
            --disable-shared &&
          make -j4
        "

    - name: Upload aria2 binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-pqc-windows
        path: aria2/src/aria2c.exe
