name: Build aria2 on Windows with OpenSSL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          make
          autoconf
          automake
          libtool
          pkg-config
          gettext-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-libxml2
          mingw-w64-x86_64-sqlite3
          mingw-w64-x86_64-libssh2
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-cppunit

    - name: Clone aria2 source
      shell: msys2 {0}
      run: |
        git clone https://github.com/aria2/aria2.git
        cd aria2
        git submodule update --init
        autoreconf -i

    - name: Configure build
      shell: msys2 {0}
      run: |
        cd aria2
        ./configure \
          --host=x86_64-w64-mingw32 \
          --with-openssl \
          --without-gnutls \
          --enable-static=yes \
          --enable-shared=no \
          --disable-websocket \
          --without-libxml2 \
          --without-libssh2 \
          --without-sqlite3 \
          --without-cares

    - name: Build aria2
      shell: msys2 {0}
      run: |
        cd aria2
        make -j$(nproc)

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-windows-openssl
        path: aria2/src/aria2c.exe
