name: Build Aria2 with PQC Support via MSYS2

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout aria2
      uses: actions/checkout@v4
      with:
        repository: aria2/aria2
        path: aria2

    - name: Install MSYS2 and dependencies
      run: |
        choco install msys2 -y
        echo "C:\tools\msys64\usr\bin" | Out-File -Append $env:GITHUB_PATH
        C:\tools\msys64\usr\bin\bash -lc "
          pacman -Sy --noconfirm &&
          pacman -S --noconfirm \
            base-devel git cmake ninja autoconf automake libtool \
            perl gcc make pkg-config zlib zlib-devel \
            libxml2 libxml2-devel sqlite sqlite-devel \
            c-ares c-ares-devel
        "

    - name: Build liboqs
      run: |
        C:\tools\msys64\usr\bin\bash -lc "
          git clone --recursive https://github.com/open-quantum-safe/liboqs.git &&
          cd liboqs &&
          mkdir build && cd build &&
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
          ninja -j$(nproc) && ninja install
        "

    - name: Build OpenSSL (official)
      run: |
        C:\tools\msys64\usr\bin\bash -lc "
          git clone https://github.com/openssl/openssl.git &&
          cd openssl &&
          git checkout openssl-3.5.3 &&
          ./Configure linux-generic64 no-shared --prefix=/usr/local/openssl &&
          make -j$(nproc) && make install_sw
        "

    - name: Build oqs-provider
      run: |
        C:\tools\msys64\usr\bin\bash -lc "
          git clone https://github.com/open-quantum-safe/oqs-provider.git &&
          cd oqs-provider &&
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release \
            -DOPENSSL_ROOT_DIR=/usr/local/openssl \
            -Dliboqs_DIR=/usr/local/lib/cmake/liboqs \
            -DCMAKE_INSTALL_PREFIX=/usr/local/oqs-provider .
          ninja -j$(nproc) && ninja install
        "

    - name: Build aria2
      run: |
        C:\tools\msys64\usr\bin\bash -lc "
          cd aria2 &&
          autoreconf -i &&
          ./configure \
            --with-openssl=/usr/local/openssl \
            --without-gnutls \
            --enable-static \
            --disable-shared &&
          make -j$(nproc)
        "

    - name: Upload aria2 binary
      uses: actions/upload-artifact@v4
      with:
        name: aria2-pqc-msys2
        path: aria2/src/aria2c.exe
