name: Build Windows EXE

on: workflow_dispatch

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: get source
        run: |
           git clone https://github.com/Molunerfinn/PicGo.git .
           del yarn.lock

      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            C:\Users\runneradmin\AppData\Local\electron
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Yarn install
        run: |
          sed -i '/initTalk/d' src/main.ts
          sed -i '/^$/d' src/main.ts
          sed -i 's/always/never/g' package.json
          yarn
          yarn global add xvfb-maybe
          yarn release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist*/*.exe
            ./src/main.ts

      
