name: Build Windows EXE

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn install
        run: |
          git clone https://github.com/Molunerfinn/PicGo.git pic
          cd pic
          rm yarn.lock
          sed -i 's/always/never/g' package.json
          yarn
          yarn global add xvfb-maybe
          yarn release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: ./pic/dist*/*.exe
          # The desired behavior if no files are found using the provided path.

      
