name: Build CPython Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout CPython source
      run: git clone https://github.com/python/cpython.git --depth 1

    - name: Cache CPython build
      uses: actions/cache@v4
      with:
        path: |
          cpython\PCBuild\amd64
          cpython\PCBuild\obj
        key: cpython-${{ runner.os }}-${{ hashFiles('cpython/PCBuild/**') }}
        restore-keys: |
          cpython-${{ runner.os }}-

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build CPython (Release x64)
      working-directory: cpython\PCBuild
      shell: cmd
      run: |
        build.bat -p x64 -c Release

    - name: Build Windows Installer (MSI)
      working-directory: cpython\Tools\msi
      shell: cmd
      run: |
        buildrelease.bat

    - name: List build artifacts
      run: |
        echo "===== CPython build output ====="
        dir /S /B cpython\PCBuild\amd64
        echo "===== MSI installer ====="
        dir /S /B cpython\Tools\msi\release\*.msi

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: cpython-windows-msi
        path: |
          cpython\Tools\msi\release\*.msi
