name: Build CPython Windows MSI Installer

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Specify the Python version/tag to build (e.g. v3.9.13, v3.11.5, main)'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 120

    steps:
    - name: Checkout specified CPython version
      run: |
        git clone --branch ${{ github.event.inputs.python_version }} --depth 1 https://github.com/python/cpython.git

    - name: Cache CPython build
      uses: actions/cache@v4
      with:
        path: |
          cpython\PCBuild\amd64
          cpython\PCBuild\obj
        key: cpython-${{ github.event.inputs.python_version }}-${{ runner.os }}-${{ hashFiles('cpython/PCBuild/**') }}
        restore-keys: |
          cpython-${{ github.event.inputs.python_version }}-${{ runner.os }}-

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build CPython (Release x64)
      working-directory: cpython\PCBuild
      shell: cmd
      run: |
        build.bat -p x64 -c Release

    - name: Build Windows MSI Installer
      working-directory: cpython\Tools\msi
      shell: cmd
      run: |
        buildrelease.bat

    - name: Upload MSI installer
      uses: actions/upload-artifact@v4
      with:
        name: cpython-windows-msi-${{ github.event.inputs.python_version }}
        path: cpython\Tools\msi\release\
