name: Build Windows EXE

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest  # 指定运行环境为 Windows

    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Yarn install
        run: |
          git clone https://github.com/Molunerfinn/PicGo.git pic
          cd pic
          yarn
          yarn global add xvfb-maybe
          vue-cli-service electron:build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: ./pic/dist*/
          # The desired behavior if no files are found using the provided path.

      
