name: Build CPython Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout CPython source
      run: git clone https://github.com/python/cpython.git --depth 1

    - name: Cache CPython build
      uses: actions/cache@v4
      with:
        path: |
          cpython\PCBuild\amd64
          cpython\PCBuild\obj
        key: cpython-${{ runner.os }}-${{ hashFiles('cpython/PCBuild/**') }}
        restore-keys: |
          cpython-${{ runner.os }}-

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build CPython
      working-directory: cpython\PCBuild
      shell: cmd
      run: |
        build.bat -p x64 -c Release

    - name: Build Windows Installer (MSI)
      working-directory: cpython\Tools\msi
      shell: cmd
      run: |
        buildrelease.bat -p x64

    - name: List build artifacts
      run: |
        echo "Build outputs:"
        dir /S /B cpython\PCBuild\amd64
        dir /S /B cpython\Tools\msi\*.msi

    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: cpython-windows-installer
        path: |
          cpython\Tools\msi\*.msi
