name: Build Surge Windows

on:
  workflow_dispatch:
    

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        run: |
          git clone https://github.com/surge-downloader/Surge.git .

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4+auto'

      - name: Build Windows exe
        run: |
          set CGO_ENABLED=0
          go build -trimpath -ldflags "-s -w" -o Surge.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Surge-windows
          path: ./*
