# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: buildexe

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: get source
        run: |
           git clone https://github.com/Molunerfinn/PicGo.git .
      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.yarn-cache
            node_modules
            ~/.cache
            ~/.electron
          key: ${{ runner.os }}-npm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Yarn install
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine32  && sudo apt-get install wine
          sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
          sed -i '/initTalk/d' src/main.ts
          sed -i '/^$/d' src/main.ts
          sed -i 's/--publish always/--win --publish never/g' package.json
          yarn
          yarn global add xvfb-maybe
          yarn release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist*/*.exe
            ./src/main.ts
