name: buildWx

on:
  workflow_dispatch

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, darwin]   # 加了 linux，方便测试
        goarch: [amd64]

    steps:
      # 拉取代码
      - name: get src
        run: |
          git clone https://github.com/ltaoo/wx_channels_download.git .

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      # 缓存 Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # 下载依赖
      - name: Download dependencies
        run: go mod download

      # 编译
      - name: Build
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/wx_video_download-${{ matrix.goos }}-${{ matrix.goarch }} .

      # 上传 artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wx_video_download-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/wx_video_download-${{ matrix.goos }}-${{ matrix.goarch }}
